<?php
/**
 * Server-side SVG template generation.
 *
 * Templates are normally built in the browser (see assets/js/template-generator.js);
 * this class provides the same output over a plain URL so the download still works
 * without JavaScript and so templates can be linked to directly.
 *
 * @package SizeGuide
 */

namespace SizeGuide;

defined( 'ABSPATH' ) || exit;

/**
 * Builds clean and guide SVG templates.
 */
class Template_Generator {

	/**
	 * Singleton instance.
	 *
	 * @var Template_Generator|null
	 */
	protected static $instance = null;

	/**
	 * Get the shared instance.
	 *
	 * @return Template_Generator
	 */
	public static function instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Register hooks.
	 */
	public function register() {
		add_action( 'init', array( $this, 'maybe_serve_download' ) );
	}

	/**
	 * Serve /?sg_template=<format-id>&sg_type=guide as an SVG download.
	 */
	public function maybe_serve_download() {
		// phpcs:disable WordPress.Security.NonceVerification.Recommended -- Public, read-only download of bundled reference data.
		if ( empty( $_GET['sg_template'] ) ) {
			return;
		}

		if ( ! Size_Guide::get_setting( 'enable_download', 1 ) ) {
			return;
		}

		$format_id = sanitize_key( wp_unslash( $_GET['sg_template'] ) );
		$type      = isset( $_GET['sg_type'] ) ? sanitize_key( wp_unslash( $_GET['sg_type'] ) ) : 'guide';
		// phpcs:enable WordPress.Security.NonceVerification.Recommended

		$format = Data_Loader::get_format( $format_id );

		if ( ! $format ) {
			wp_die(
				esc_html__( 'That size template could not be found.', 'size-guide' ),
				esc_html__( 'Size Guide', 'size-guide' ),
				array( 'response' => 404 )
			);
		}

		$svg      = self::build_svg( $format, 'clean' === $type ? 'clean' : 'guide' );
		$filename = sanitize_file_name( $format['id'] . '-' . $type . '.svg' );

		nocache_headers();
		header( 'Content-Type: image/svg+xml; charset=utf-8' );
		header( 'Content-Disposition: attachment; filename="' . $filename . '"' );
		header( 'Content-Length: ' . strlen( $svg ) );

		echo $svg; // phpcs:ignore WordPress.Security.EscapingOutput.OutputNotEscaped -- Built from escaped values in build_svg().
		exit;
	}

	/**
	 * Direct download URL for a format.
	 *
	 * @param string $format_id Format id.
	 * @param string $type      "clean" or "guide".
	 * @return string
	 */
	public static function download_url( $format_id, $type = 'guide' ) {
		return add_query_arg(
			array(
				'sg_template' => rawurlencode( $format_id ),
				'sg_type'     => rawurlencode( $type ),
			),
			home_url( '/' )
		);
	}

	/**
	 * Build the SVG document for one format.
	 *
	 * @param array  $format Normalised format record.
	 * @param string $type   "clean" or "guide".
	 * @return string
	 */
	public static function build_svg( array $format, $type = 'guide' ) {
		$unit   = $format['unit'];
		$width  = (float) $format['width'];
		$height = (float) $format['height'];
		$bleed  = (float) $format['bleed'];

		$doc_width  = $width + ( $bleed * 2 );
		$doc_height = $height + ( $bleed * 2 );

		// SVG user units: pixels stay 1:1, physical units get a real-world size.
		$svg_unit = ( 'px' === $unit ) ? '' : $unit;

		$parts   = array();
		$parts[] = '<?xml version="1.0" encoding="UTF-8"?>';
		$parts[] = sprintf(
			'<svg xmlns="http://www.w3.org/2000/svg" width="%1$s%3$s" height="%2$s%3$s" viewBox="0 0 %1$s %2$s" role="img" aria-label="%4$s">',
			self::num( $doc_width ),
			self::num( $doc_height ),
			esc_attr( $svg_unit ),
			esc_attr( $format['platform_name'] . ' ' . $format['name'] )
		);

		$parts[] = sprintf(
			'<title>%s</title><desc>%s</desc>',
			esc_html( $format['platform_name'] . ' — ' . $format['name'] ),
			esc_html(
				sprintf(
					/* translators: 1: width, 2: height, 3: unit, 4: aspect ratio */
					__( '%1$s x %2$s %3$s, aspect ratio %4$s. Generated by the Size Guide plugin.', 'size-guide' ),
					$format['width'],
					$format['height'],
					$unit,
					$format['aspect_ratio']
				)
			)
		);

		// The artboard itself.
		$parts[] = sprintf(
			'<rect x="0" y="0" width="%s" height="%s" fill="#ffffff"/>',
			self::num( $doc_width ),
			self::num( $doc_height )
		);

		if ( 'clean' === $type ) {
			$parts[] = '</svg>';
			return implode( "\n", $parts );
		}

		$stroke = max( $doc_width, $doc_height ) / 600;
		$font   = max( $doc_width, $doc_height ) / 45;

		$parts[] = '<g id="size-guide-guides" fill="none">';

		// Bleed edge.
		if ( $bleed > 0 ) {
			$parts[] = sprintf(
				'<rect x="0" y="0" width="%s" height="%s" stroke="#e11d48" stroke-width="%s" stroke-dasharray="%s"/>',
				self::num( $doc_width ),
				self::num( $doc_height ),
				self::num( $stroke ),
				self::num( $stroke * 6 )
			);
		}

		// Trim / canvas.
		$parts[] = sprintf(
			'<rect x="%s" y="%s" width="%s" height="%s" stroke="#111827" stroke-width="%s"/>',
			self::num( $bleed ),
			self::num( $bleed ),
			self::num( $width ),
			self::num( $height ),
			self::num( $stroke )
		);

		// Margin.
		$margin = $format['margin'];
		if ( $margin ) {
			$parts[] = sprintf(
				'<rect x="%s" y="%s" width="%s" height="%s" stroke="#f59e0b" stroke-width="%s" stroke-dasharray="%s"/>',
				self::num( $bleed + $margin['left'] ),
				self::num( $bleed + $margin['top'] ),
				self::num( $width - $margin['left'] - $margin['right'] ),
				self::num( $height - $margin['top'] - $margin['bottom'] ),
				self::num( $stroke ),
				self::num( $stroke * 4 )
			);
		}

		// Safe zone.
		$safe = $format['safe_zone'];
		if ( $safe ) {
			$parts[] = sprintf(
				'<rect x="%s" y="%s" width="%s" height="%s" stroke="#16a34a" stroke-width="%s" stroke-dasharray="%s"/>',
				self::num( $bleed + $safe['left'] ),
				self::num( $bleed + $safe['top'] ),
				self::num( $width - $safe['left'] - $safe['right'] ),
				self::num( $height - $safe['top'] - $safe['bottom'] ),
				self::num( $stroke ),
				self::num( $stroke * 3 )
			);
		}

		// Centre lines.
		$parts[] = sprintf(
			'<path d="M %1$s 0 V %2$s M 0 %3$s H %4$s" stroke="#93c5fd" stroke-width="%5$s" stroke-dasharray="%6$s"/>',
			self::num( $doc_width / 2 ),
			self::num( $doc_height ),
			self::num( $doc_height / 2 ),
			self::num( $doc_width ),
			self::num( $stroke * 0.75 ),
			self::num( $stroke * 3 )
		);

		$parts[] = '</g>';

		// Label block.
		$parts[] = sprintf(
			'<text x="%s" y="%s" font-family="Helvetica, Arial, sans-serif" font-size="%s" fill="#6b7280">%s</text>',
			self::num( $bleed + ( $font * 0.5 ) ),
			self::num( $bleed + ( $font * 1.4 ) ),
			self::num( $font ),
			esc_html(
				sprintf(
					'%s %s x %s %s · %s',
					$format['name'],
					$format['width'],
					$format['height'],
					$unit,
					$format['aspect_ratio']
				)
			)
		);

		$parts[] = '</svg>';

		return implode( "\n", $parts );
	}

	/**
	 * Format a number for SVG output without trailing noise.
	 *
	 * @param float $value Number.
	 * @return string
	 */
	protected static function num( $value ) {
		$value = round( (float) $value, 3 );
		return rtrim( rtrim( number_format( $value, 3, '.', '' ), '0' ), '.' );
	}
}
